name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH Agent
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Run Deployment Script
      run: |
        ssh -o StrictHostKeyChecking=no ${SSH_USER}@${SSH_HOST} 'cd ${{ secrets.PROJECT_PATH }} && ./.scripts/deploy.sh'
